# Generated by Django 4.2.16 on 2024-10-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('brand', models.CharField(max_length=30)),
                ('guarantee', models.CharField(max_length=30)),
                ('discount', models.PositiveSmallIntegerField()),
                ('material', models.CharField(max_length=30)),
                ('rating', models.FloatField()),
                ('stock', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
